=== MaurickCreation/workspace/lalahmode-parent/lalahmode-domain/cave.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT CAVE (APPELLATION)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT APPELLATION (NOM_APPELLATION,CHATEAU+)>
<!ATTLIST APPELLATION
    id CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT NOM_APPELLATION (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT CHATEAU (NOM_CHATEAU,ADRESSE_CHATEAU,TEL_CHATEAU,BOUTEILLE+)>
<!ATTLIST CHATEAU
    dep CDATA #IMPLIED
    id CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT NOM_CHATEAU (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT ADRESSE_CHATEAU (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT TEL_CHATEAU (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT BOUTEILLE (NOM,CUVEE+)>
<!ATTLIST BOUTEILLE
    id CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT NOM (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT CUVEE (NOMBRE,PRIX)*>
<!ATTLIST CUVEE
    id CDATA #IMPLIED
    annee CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT NOMBRE (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT PRIX (#PCDATA)>

=== MaurickCreation/workspace/lalahmode-parent/lalahmode-domain/cave.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<?xml-stylesheet type="text/xsl" href=""?>
<!DOCTYPE CAVE SYSTEM "cave.dtd">

<CAVE>
<APPELLATION id="1" >
    <NOM_APPELLATION>Cote de bourg</NOM_APPELLATION>
    <CHATEAU id="1" dep="33">
      <NOM_CHATEAU>Chateau bellevue</NOM_CHATEAU>
      <ADRESSE_CHATEAU>12 rue du pont 33056 Libourne</ADRESSE_CHATEAU>
      <TEL_CHATEAU>0556565656</TEL_CHATEAU>
      <BOUTEILLE id="1">
                 <NOM>Superieur</NOM>
                 <CUVEE annee="2000" id="1">
                        <NOMBRE>100</NOMBRE>
                        <PRIX>10</PRIX>
                 </CUVEE>
                 <CUVEE annee="1999" id="2">
                        <NOMBRE>50</NOMBRE>
                        <PRIX>15</PRIX>
                 </CUVEE>
      </BOUTEILLE>
      <BOUTEILLE id="2">
                 <NOM>Rose</NOM>
                 <CUVEE annee="2000" id="3">
                        <NOMBRE>100</NOMBRE>
                        <PRIX>5</PRIX>
                 </CUVEE>
                 <CUVEE annee="1999" id="4">
                        <NOMBRE>50</NOMBRE>
                        <PRIX>3</PRIX>
                 </CUVEE>
      </BOUTEILLE>
    </CHATEAU>
    <CHATEAU id="2" dep="33">
      <NOM_CHATEAU>Chateau lacroute</NOM_CHATEAU>
      <ADRESSE_CHATEAU>13 rue de la soif 33024 Bourg</ADRESSE_CHATEAU>
      <TEL_CHATEAU>0556565656</TEL_CHATEAU>
        <BOUTEILLE id="3">
                 <NOM>Superieur</NOM>
                 <CUVEE annee="2000" id="5">
                        <NOMBRE>100</NOMBRE>
                        <PRIX>5</PRIX>
                 </CUVEE>
                 <CUVEE annee="1999" id="6">
                        <NOMBRE>50</NOMBRE>
                        <PRIX>3</PRIX>
                 </CUVEE>
      </BOUTEILLE>
    </CHATEAU>
</APPELLATION>

<APPELLATION id="2">
    <NOM_APPELLATION>Saint Emilion</NOM_APPELLATION>
    <CHATEAU id="3" dep="33">
        <NOM_CHATEAU>Chateau Margot</NOM_CHATEAU>
        <ADRESSE_CHATEAU>Au bord de la riviere 33012 Saint Emilion</ADRESSE_CHATEAU>
        <TEL_CHATEAU>055656565656</TEL_CHATEAU>
        <BOUTEILLE id="4">
                 <NOM>Blanc</NOM>
                 <CUVEE annee="2003" id="7">
                        <NOMBRE>1000</NOMBRE>
                        <PRIX>8</PRIX>
                 </CUVEE>
                 <CUVEE annee="2002" id="8">
                        <NOMBRE>500</NOMBRE>
                        <PRIX>10</PRIX>
                 </CUVEE>
      </BOUTEILLE>
      <BOUTEILLE id="5">
                 <NOM>Rouge</NOM>
                 <CUVEE annee="2001" id="9">
                        <NOMBRE>100</NOMBRE>
                        <PRIX>12</PRIX>
                 </CUVEE>
                 <CUVEE annee="2000" id="10">
                        <NOMBRE>75</NOMBRE>
                        <PRIX>15</PRIX>
                 </CUVEE>
      </BOUTEILLE>
    </CHATEAU>
    <CHATEAU id="4" dep="17">
        <NOM_CHATEAU>Chateau Moulinsard</NOM_CHATEAU>
        <ADRESSE_CHATEAU>Allée du Capitaine Adhoc</ADRESSE_CHATEAU>
        <TEL_CHATEAU>0556123656</TEL_CHATEAU>
        <BOUTEILLE id="6">
                 <NOM>Vin de table</NOM>
                 <CUVEE annee="2005" id="10">
                        <NOMBRE>10000</NOMBRE>
                        <PRIX>2</PRIX>
                 </CUVEE>
        </BOUTEILLE>
        <BOUTEILLE id="10">
                 <NOM>Vinaigre de vin</NOM>
                 <CUVEE annee="2005" id="11">
                        <NOMBRE>20000</NOMBRE>
                        <PRIX>1</PRIX>
                 </CUVEE>
        </BOUTEILLE>
    </CHATEAU>
</APPELLATION>

<APPELLATION id="3">
    <NOM_APPELLATION>Jurancon</NOM_APPELLATION>
    <CHATEAU id="6" dep="94">
        <NOM_CHATEAU>Chateau de la belle au bois dormant</NOM_CHATEAU>
        <ADRESSE_CHATEAU>12, allée de Mickey 94051 Eurodisney</ADRESSE_CHATEAU>
        <TEL_CHATEAU>0558965656</TEL_CHATEAU>
        <BOUTEILLE id="7">
                 <NOM>Vin de nains</NOM>
                 <CUVEE annee="2000" id="12">
                        <NOMBRE>7</NOMBRE>
                        <PRIX>50</PRIX>
                 </CUVEE>
                 <CUVEE annee="2001" id="13">
                        <NOMBRE>7</NOMBRE>
                        <PRIX>40</PRIX>
                 </CUVEE>
        </BOUTEILLE>
    </CHATEAU>
</APPELLATION>

<APPELLATION id="4">
    <NOM_APPELLATION>Medoc</NOM_APPELLATION>
    <CHATEAU id="7" dep="33">
        <NOM_CHATEAU>Chateau Bois de Roc</NOM_CHATEAU>
        <ADRESSE_CHATEAU>Au fond du bois à coté du roc 33056 Lesparre</ADRESSE_CHATEAU>
        <TEL_CHATEAU>0556563459</TEL_CHATEAU>
                <BOUTEILLE id="8">
                 <NOM>Superieur</NOM>
                 <CUVEE annee="2003" id="14">
                        <NOMBRE>100</NOMBRE>
                        <PRIX>20</PRIX>
                 </CUVEE>
                 <CUVEE annee="2004" id="15">
                        <NOMBRE>500</NOMBRE>
                        <PRIX>15</PRIX>
                 </CUVEE>
        </BOUTEILLE>
    </CHATEAU>
    <CHATEAU id="8" dep="33">
        <NOM_CHATEAU>Chateau Haut Blaignan</NOM_CHATEAU>
        <ADRESSE_CHATEAU>En haut de blaignan 330567 Blaignan</ADRESSE_CHATEAU>
        <TEL_CHATEAU>0558765656</TEL_CHATEAU>
        <BOUTEILLE id="9">
                 <NOM>Superieur</NOM>
                 <CUVEE annee="2003" id="16">
                        <NOMBRE>100</NOMBRE>
                        <PRIX>25</PRIX>
                 </CUVEE>
                 <CUVEE annee="2004" id="17">
                        <NOMBRE>500</NOMBRE>
                        <PRIX>10</PRIX>
                 </CUVEE>
        </BOUTEILLE>
    </CHATEAU>
</APPELLATION>
</CAVE>
