=== MaurickCreation/workspace/lalahmode-parent/lalahmode-domain/commande.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT LISTE_COMMANDES (COMMANDE)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT COMMANDE (CLIENT,DATE,CUVEE+,DATE_VALID)*>
<!ATTLIST COMMANDE
    id CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT CLIENT (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT DATE (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT CUVEE (NOMBRE)+>
<!ATTLIST CUVEE
    id CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT NOMBRE (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT DATE_VALID (#PCDATA)>

=== MaurickCreation/workspace/Vieillecave/commande.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<?xml-stylesheet type="text/xsl" href=""?>
<!DOCTYPE LISTE_COMMANDES SYSTEM "commande.dtd">
<LISTE_COMMANDES>
	<COMMANDE id="1">
		<CLIENT>toto</CLIENT>
		<DATE>23/03/2006</DATE>
		<CUVEE id="1">
                    <NOMBRE>10</NOMBRE>
		</CUVEE>
		<CUVEE id="10">
                    <NOMBRE>15</NOMBRE>
		</CUVEE>
		<DATE_VALID>00/00/0000</DATE_VALID>
	</COMMANDE>
	<COMMANDE id="2">
		<CLIENT>toto</CLIENT>
		<DATE>23/03/2006</DATE>
		<CUVEE id="7">
                    <NOMBRE>3</NOMBRE>
		</CUVEE>
		<DATE_VALID>23/03/2006</DATE_VALID>
	</COMMANDE>
</LISTE_COMMANDES>
